import * as os from 'node:os';
import { loadContextFiles, buildContextPrompt } from './context.js';
import { loadAllSkills, matchSkills, type Skill } from '../skills/index.js';
import { getMcpStatus } from './mcp.js';

export function buildSystemPrompt(pm: { pm: string; run: string }, summary?: string, userMessage?: string): string {
  const cwd = process.cwd();
  const platform = os.platform();
  const date = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
  const contextFiles = loadContextFiles();
  const contextPrompt = buildContextPrompt(contextFiles);

  const allSkills = loadAllSkills();
  const matchedSkills = userMessage ? matchSkills(userMessage, allSkills) : [];

  const base = `You are ai-cli, a minimal terminal AI assistant.

About ai-cli:
- Created by nishimiya (x.com/nishimiya)
- Built with Vercel AI SDK and AI Gateway
- Supports multiple AI providers through gateway routing

Tool usage:
- BE PROACTIVE: If you can answer with a tool, USE IT immediately
- Never say "I can't" or "I don't have access" if a tool can help
- "what time is it?" -> run \`date\` command
- "what's the weather?" -> use weather tool
- "what files are here?" -> list the directory
- Action first, minimal explanation after
- For search tools (perplexity_search, parallel_search): ALWAYS summarize the results in your response
- For fetchUrl: ALWAYS summarize the fetched content in your response

Output rules (CRITICAL - MUST FOLLOW):
- NEVER use markdown: no **bold**, no *italic*, no # headers, no \`backticks\`, no bullet points with -
- Plain text only, no formatting whatsoever
- No emojis ever
- Be concise, minimal responses
- After file/memory tools only, output NOTHING (but search/fetch tools MUST have a response)

Environment:
- Directory: ${cwd}
- Platform: ${platform}
- Date: ${date}
- Package manager: ${pm.pm} (run scripts with "${pm.run}")

Preferences:
- Always use TypeScript unless told otherwise
- For Next.js: use --ts flag, App Router, src directory

Git commits:
- One line only: "type: description" (feat, fix, docs, refactor, test, chore)
- Lowercase, no period at end
- NEVER co-author or mention AI/assistant/model
- NEVER add "Generated by" or attribution lines

Slash commands (tell user to type these):
- /git commit - ai-generated commit message
- /git status|diff|push|pull|log|stash|branch - git operations
- /model <name> - switch model
- /help - list all commands
When user asks to commit, push, or switch models, tell them the slash command to type.`;

  let prompt = base;
  if (contextPrompt) prompt += `\n\n${contextPrompt}`;

  if (allSkills.length > 0) {
    const skillsList = allSkills.map(s => `- ${s.name}: ${s.description || 'no description'}`).join('\n');
    prompt += `\n\nInstalled skills (use /skills to manage):\n${skillsList}`;
  }

  if (matchedSkills.length > 0) {
    const skillsPrompt = matchedSkills.map(s => `<skill name="${s.name}">\n${s.content}\n</skill>`).join('\n\n');
    prompt += `\n\nActive skills for this query:\n${skillsPrompt}`;
  }

  const mcpServers = getMcpStatus();
  const connectedMcp = mcpServers.filter(s => s.connected);
  if (connectedMcp.length > 0) {
    const mcpList = connectedMcp.map(s => `- ${s.name}`).join('\n');
    prompt += `\n\nMCP servers connected (tools prefixed with server name):\n${mcpList}`;
  }

  if (summary) prompt += `\n\nPrevious session context:\n${summary}`;
  return prompt;
}

export const toolActions: Record<string, string> = {
  readFile: 'reading...',
  writeFile: 'writing...',
  editFile: 'editing...',
  deleteFile: 'deleting...',
  copyFile: 'copying...',
  renameFile: 'renaming...',
  createFolder: 'creating...',
  listDirectory: 'listing...',
  findFiles: 'searching...',
  searchInFiles: 'searching...',
  fileInfo: 'checking...',
  runCommand: 'running...',
  startProcess: 'starting...',
  readProcessLogs: 'reading logs...',
  killProcess: 'stopping...',
  memory: 'remembering...',
  weather: 'checking weather...',
  fetchUrl: 'fetching...',
  perplexity_search: 'searching...',
  parallel_search: 'searching...',
};
